# dataset.py: 데이터셋 불러오기에 사용되는 파라미터
# =======================================
data_path: 'data/423_BE1_IZ1/KFEMS.HALLA.01.DC01.IP001_202205_feeder_00_tag_IO_5SEC_MIX_423_BE1_IZ1.csv'
interval_path: "data/intervals.json"
standardize: True

file_num: 1000
Ntrainpoints: 5000
Ntestpoints: 1000
number_of_noisy_obs: 5

# model.py: 모델 초기화에 들어가는 파라미터
# =======================================
lstm_size: 128
latent_size: 20
input_size: 2 
seq_size: 150
num_lyears: 1
batch_size: 5
attention_size: 2
sample_reps: 20
directions: 2

# main.py: 모델 사용에 들어가는 파라미터
# =======================================
train: True
optimizer_choice: 'AdamW'
learning_rate: 1e-2
epochs: 8
lambda_kl: 0

# Not Used Yet
# =======================================
lambda_max: 1
lambda_update_rate: 0.1
save_bad_img: "No" #Yes
eta: 0.01